# Generated by Django 5.2.5 on 2025-09-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcesApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceRating',
        ),
    ]
