# Generated by Django 5.2.5 on 2026-07-26 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0001_initial'),
        ('studentsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enrollment Request', 'verbose_name_plural': 'Enrollment Requests'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__username'], 'verbose_name': 'Pupil', 'verbose_name_plural': 'Pupils'},
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='pupil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='classesApp.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent email used for automatic linking.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'pupil'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
