# Generated by Django 5.2.5 on 2025-08-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsApp', '0002_remove_parent_student'),
        ('studentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parentsApp.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
