# Generated by Django 5.2.5 on 2025-08-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0002_student_parent_alter_student_parent_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_contact',
        ),
    ]
