# Generated by Django 5.2.5 on 2026-07-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsApp', '0002_alter_parent_options_alter_parent_user'),
        ('studentsApp', '0002_alter_enrollmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent or guardian linked to this pupil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupils', to='parentsApp.parent'),
        ),
    ]
