# Generated by Django 5.2.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "schoolsApp",
            "0002_school_paystack_recipient_code_and_more",
        ),
        (
            "studentsApp",
            "0003_student_parent",
        ),
    ]


    operations = [

        migrations.AddField(
            model_name="enrollmentrequest",
            name="school",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_requests",
                to="schoolsApp.school",
            ),
        ),


        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schoolsApp.school",
            ),
        ),

    ]