# Generated by Django 5.2.5 on 2025-08-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsApp', '0002_remove_parent_student'),
        ('studentsApp', '0004_alter_student_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_contact', to='parentsApp.parent'),
        ),
    ]
