# Generated by Django 5.2.5 on 2026-07-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsApp', '0002_school_paystack_recipient_code_and_more'),
        ('studentsApp', '0004_enrollmentrequest_school_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='schoolsApp.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolsApp.school'),
        ),
    ]
