# Generated by Django 5.2.5 on 2026-05-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0007_enrollmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
