# Generated by Django 5.2.5 on 2026-05-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0003_subjects'),
        ('studentsApp', '0008_alter_enrollmentrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Any additional info from parent'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='pupil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classesApp.classroom'),
        ),
    ]
