# Generated by Django 5.2.5 on 2026-07-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0009_alter_enrollmentrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'verbose_name': 'Enrollment Request', 'verbose_name_plural': 'Enrollment Requests'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Pupil', 'verbose_name_plural': 'Pupils'},
        ),
    ]
