# Generated by Django 5.2.5 on 2026-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('pupil', 'Pupil'), ('parent', 'Parent')], default='pupil', max_length=20),
        ),
    ]
