# Generated by Django 5.2.5 on 2026-07-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0002_alter_attendance_status_and_more'),
        ('studentsApp', '0010_alter_enrollmentrequest_options_and_more'),
        ('teachersApp', '0004_pupilreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsApp.student', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachersApp.teacher', verbose_name='Teacher'),
        ),
    ]
