# Generated by Django 5.2.5 on 2026-07-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classesApp', '0001_initial'),
        ('studentsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('final', 'Final Exam')], default='term1', max_length=10)),
                ('exam_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classesApp.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classesApp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examsApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsApp.student', verbose_name='Pupil')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
