# Generated by Django 5.2.5 on 2025-08-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsApp', '0002_alter_exam_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
