# Generated by Django 5.2.5 on 2026-07-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsApp', '0004_exam_description_exam_term_examresult'),
        ('studentsApp', '0010_alter_enrollmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsApp.student', verbose_name='Pupil'),
        ),
    ]
