# Generated by Django 5.2.5 on 2026-07-27 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Percentage retained by Nexor Labs', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='paystack_subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
