# Generated by Django 5.2.5 on 2025-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
