# Generated by Django 5.2.5 on 2026-07-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0001_initial'),
        ('schoolsApp', '0002_school_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['school__name', 'name', 'section'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this class belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schoolsApp.school'),
        ),
    ]
