# Generated by Django 5.2.5 on 2025-08-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0002_alter_classroom_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
