# Generated by Django 5.2.5 on 2025-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0003_subjects'),
        ('teachersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ManyToManyField(related_name='assigned_teachers', to='classesApp.classroom'),
        ),
    ]
