# Generated by Django 5.2.5 on 2026-07-26 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0001_initial'),
        ('teachersApp', '0002_alter_teacher_hire_date_alter_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pupilreport',
            options={'ordering': ['-academic_year', 'term']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__username'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='pupilreport',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to='classesApp.classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='classesApp.subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
