# Generated by Django 5.2.5 on 2025-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0003_subjects'),
        ('teachersApp', '0002_teacher_assigned_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='assigned_subjects', to='classesApp.subjects'),
        ),
    ]
