# Generated by Django 5.2.5 on 2026-07-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0010_alter_enrollmentrequest_options_and_more'),
        ('teachersApp', '0003_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupilReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=1)),
                ('academic_year', models.CharField(max_length=9)),
                ('comment', models.TextField(blank=True, help_text="Teacher's comment on pupil progress")),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studentsApp.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachersApp.teacher')),
            ],
            options={
                'unique_together': {('pupil', 'term', 'academic_year')},
            },
        ),
    ]
