# Generated by Django 5.2.5 on 2026-07-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesApp', '0002_alter_classroom_options_alter_subjects_options_and_more'),
        ('studentsApp', '0005_alter_enrollmentrequest_school_alter_student_school'),
        ('teachersApp', '0003_alter_assignment_options_alter_pupilreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pupilreport',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_records', to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classesApp.classroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classesApp.subjects'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='pupilreport',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pupil_reports', to='teachersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classesApp.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='classesApp.subjects'),
        ),
        migrations.AddConstraint(
            model_name='pupilreport',
            constraint=models.UniqueConstraint(fields=('pupil', 'term', 'academic_year'), name='unique_pupil_term_academic_year_report'),
        ),
    ]
