# Generated by Django 5.2.5 on 2026-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersApp', '0005_assignment_behaviorlog_timetable_academicrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='exam_type',
            field=models.CharField(choices=[('TEST', 'Test'), ('EXAM', 'Exam')], max_length=10),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='conduct_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='is_report_card_remark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pupilreport',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
