# Generated by Django 5.2.5 on 2026-07-26 23:30

import django.db.models.deletion
import django.utils.timezone
import settingsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Green Apple Academy', max_length=200)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('academic_year', models.CharField(default='2026', max_length=20)),
                ('current_term', models.CharField(default='Term 1', max_length=20)),
                ('reception_enabled', models.BooleanField(default=True)),
                ('pre_grade_enabled', models.BooleanField(default=True)),
                ('school_open', models.TimeField(default='07:00')),
                ('school_close', models.TimeField(default='17:00')),
                ('primary_color', models.CharField(default='#198754', max_length=20)),
                ('secondary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Enterprise', 'Enterprise')], default='Starter', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=settingsApp.models.default_subscription_expiry)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=100)),
                ('max_pupils', models.PositiveIntegerField(default=1000)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='settingsApp.schoolsettings')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
