# Generated by Django 5.2.5 on 2025-08-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
    ]
