# Generated by Django 5.2.5 on 2026-07-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsApp', '0002_alter_parent_options_alter_parent_user'),
        ('schoolsApp', '0002_school_paystack_recipient_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='schoolsApp.school'),
        ),
    ]
